//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DohomeApplicationAPI.MMO001_GetBinAssignloc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://dohome.co.th/HandheldOutound/MM", ConfigurationName="MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub")]
    public interface SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub(DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse> SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubAsync(DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_ASSIGNLOC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mANDTField;
        
        private string mATERIALField;
        
        private string uNITOFMEASUREField;
        
        private string bIN_CODEField;
        
        private string lOCTYPEField;
        
        private string wERKSField;
        
        private string sTORAGE_LOCField;
        
        private string dEFAULT_BINField;
        
        private decimal mAXSTOCKField;
        
        private bool mAXSTOCKFieldSpecified;
        
        private decimal rOWORDERField;
        
        private bool rOWORDERFieldSpecified;
        
        private decimal pUTQTYField;
        
        private bool pUTQTYFieldSpecified;
        
        private decimal pUTLEVELField;
        
        private bool pUTLEVELFieldSpecified;
        
        private decimal mINSTOCKField;
        
        private bool mINSTOCKFieldSpecified;
        
        private string sPANTYPEField;
        
        private decimal sPANWIDEField;
        
        private bool sPANWIDEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
                this.RaisePropertyChanged("MANDT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATERIAL {
            get {
                return this.mATERIALField;
            }
            set {
                this.mATERIALField = value;
                this.RaisePropertyChanged("MATERIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UNITOFMEASURE {
            get {
                return this.uNITOFMEASUREField;
            }
            set {
                this.uNITOFMEASUREField = value;
                this.RaisePropertyChanged("UNITOFMEASURE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BIN_CODE {
            get {
                return this.bIN_CODEField;
            }
            set {
                this.bIN_CODEField = value;
                this.RaisePropertyChanged("BIN_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOCTYPE {
            get {
                return this.lOCTYPEField;
            }
            set {
                this.lOCTYPEField = value;
                this.RaisePropertyChanged("LOCTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string STORAGE_LOC {
            get {
                return this.sTORAGE_LOCField;
            }
            set {
                this.sTORAGE_LOCField = value;
                this.RaisePropertyChanged("STORAGE_LOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DEFAULT_BIN {
            get {
                return this.dEFAULT_BINField;
            }
            set {
                this.dEFAULT_BINField = value;
                this.RaisePropertyChanged("DEFAULT_BIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal MAXSTOCK {
            get {
                return this.mAXSTOCKField;
            }
            set {
                this.mAXSTOCKField = value;
                this.RaisePropertyChanged("MAXSTOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MAXSTOCKSpecified {
            get {
                return this.mAXSTOCKFieldSpecified;
            }
            set {
                this.mAXSTOCKFieldSpecified = value;
                this.RaisePropertyChanged("MAXSTOCKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal ROWORDER {
            get {
                return this.rOWORDERField;
            }
            set {
                this.rOWORDERField = value;
                this.RaisePropertyChanged("ROWORDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ROWORDERSpecified {
            get {
                return this.rOWORDERFieldSpecified;
            }
            set {
                this.rOWORDERFieldSpecified = value;
                this.RaisePropertyChanged("ROWORDERSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal PUTQTY {
            get {
                return this.pUTQTYField;
            }
            set {
                this.pUTQTYField = value;
                this.RaisePropertyChanged("PUTQTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PUTQTYSpecified {
            get {
                return this.pUTQTYFieldSpecified;
            }
            set {
                this.pUTQTYFieldSpecified = value;
                this.RaisePropertyChanged("PUTQTYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal PUTLEVEL {
            get {
                return this.pUTLEVELField;
            }
            set {
                this.pUTLEVELField = value;
                this.RaisePropertyChanged("PUTLEVEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PUTLEVELSpecified {
            get {
                return this.pUTLEVELFieldSpecified;
            }
            set {
                this.pUTLEVELFieldSpecified = value;
                this.RaisePropertyChanged("PUTLEVELSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal MINSTOCK {
            get {
                return this.mINSTOCKField;
            }
            set {
                this.mINSTOCKField = value;
                this.RaisePropertyChanged("MINSTOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MINSTOCKSpecified {
            get {
                return this.mINSTOCKFieldSpecified;
            }
            set {
                this.mINSTOCKFieldSpecified = value;
                this.RaisePropertyChanged("MINSTOCKSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SPANTYPE {
            get {
                return this.sPANTYPEField;
            }
            set {
                this.sPANTYPEField = value;
                this.RaisePropertyChanged("SPANTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal SPANWIDE {
            get {
                return this.sPANWIDEField;
            }
            set {
                this.sPANWIDEField = value;
                this.RaisePropertyChanged("SPANWIDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SPANWIDESpecified {
            get {
                return this.sPANWIDEFieldSpecified;
            }
            set {
                this.sPANWIDEFieldSpecified = value;
                this.RaisePropertyChanged("SPANWIDESpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZHH_GET_BIN_ASSIGNLOC", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_BINCODE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_LGORT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_MATNR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_WERKS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DohomeApplicationAPI.MMO001_GetBinAssignloc.ZMM_ASSIGNLOC[] O_ASSIGNLOC;
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest() {
        }
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest(string I_BINCODE, string I_LGORT, string I_MATNR, string I_WERKS, DohomeApplicationAPI.MMO001_GetBinAssignloc.ZMM_ASSIGNLOC[] O_ASSIGNLOC) {
            this.I_BINCODE = I_BINCODE;
            this.I_LGORT = I_LGORT;
            this.I_MATNR = I_MATNR;
            this.I_WERKS = I_WERKS;
            this.O_ASSIGNLOC = O_ASSIGNLOC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZHH_GET_BIN_ASSIGNLOC.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DohomeApplicationAPI.MMO001_GetBinAssignloc.ZMM_ASSIGNLOC[] O_ASSIGNLOC;
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse() {
        }
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse(DohomeApplicationAPI.MMO001_GetBinAssignloc.ZMM_ASSIGNLOC[] O_ASSIGNLOC) {
            this.O_ASSIGNLOC = O_ASSIGNLOC;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubChannel : DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubClient : System.ServiceModel.ClientBase<DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub>, DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub {
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubClient() {
        }
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub(DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest request) {
            return base.Channel.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub(request);
        }
        
        public void SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub(string I_BINCODE, string I_LGORT, string I_MATNR, string I_WERKS, ref DohomeApplicationAPI.MMO001_GetBinAssignloc.ZMM_ASSIGNLOC[] O_ASSIGNLOC) {
            DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest inValue = new DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest();
            inValue.I_BINCODE = I_BINCODE;
            inValue.I_LGORT = I_LGORT;
            inValue.I_MATNR = I_MATNR;
            inValue.I_WERKS = I_WERKS;
            inValue.O_ASSIGNLOC = O_ASSIGNLOC;
            DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse retVal = ((DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub)(this)).SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub(inValue);
            O_ASSIGNLOC = retVal.O_ASSIGNLOC;
        }
        
        public System.Threading.Tasks.Task<DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubResponse> SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubAsync(DohomeApplicationAPI.MMO001_GetBinAssignloc.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubRequest request) {
            return base.Channel.SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oubAsync(request);
        }

        internal void SI_MMO001_ZHH_GET_BIN_ASSIGNLOC_Sync_oub(string v, string slocCode, string code, string siteCode, object arrAssign)
        {
            throw new NotImplementedException();
        }
    }
}
